//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public Nullable<short> x { get; set; }
        public Nullable<short> y { get; set; }
        public Nullable<bool> is_alive { get; set; }
        public long id { get; set; }
    }
}
